version: "3.1"
networks:
  c-net:
    driver: bridge
  r-net:
    driver: bridge
  l-net:
    driver: bridge

services:
  goods:
    image: goods
    build: ./
    ports:
      - "8080:8080"
    networks:
      - c-net
      - r-net
      - l-net
    depends_on:
      - postgresql
      - redis
      - nats
    restart: unless-stopped

  postgresql:
    image: postgres:15.1
    environment:
      POSTGRES_DB: example
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: "/var/lib/postgresql/data/pgdata"
    container_name: 'postgresql'
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d example"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
    networks:
      - c-net

  redis:
    image: redis:7.2.0
    ports:
      - 6379:6379
    restart: unless-stopped
    networks:
      - r-net

  nats:
    image: nats:2.9.21
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
    networks:
      - l-net

  clickhouse:
    image: clickhouse/clickhouse-server:22.8-alpine
    environment:
      CLICKHOUSE_DB: clickdb
      CLICKHOUSE_USER: clickuser
      CLICKHOUSE_PASSWORD: password1
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    ports:
    - "8123:8123"
    - "9000:9000"
    - "9009:9009"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    depends_on:
      - nats
    networks:
      - l-net